name: VScode client release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: Setup | Checkout
      - uses: actions/checkout@v3
      - name: Setup | pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Setup | Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: pnpm i
      - run: pnpm run postinstall
      - run: pnpm run package
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
